### ISSUE TITLE
code is not properly indented for almost whole project 

### ISSUE THREAD

**Issue by alifaroo-q** [anthonypz/Contactr#22]
source code needs to be properly indented.

as a result, this will improve code readability.

**Comment by alifaroo-q** [comment]
> source code needs to be properly indented.
> 
> as a result, this will improve code readability.

@anthonypz can you assign me this.

**Comment by anthonypz** [comment]
@alifaroo-q Sorry for the late reply. What sort of indentation problems are you referring to? 

This is a small, forked project from 100devs. There are many people forking from the original project [here](https://github.com/100devs/todo-mvc-auth-local). It might be a good idea to submit a PR there so that more people benefit from the resulting changes. If you would like to contribute here instead, let me know and I can discuss that with the team as we're on a very short deadline for this project.

**Comment by alifaroo-q** [comment]
ok, my bad I did not realize this was a forked repo. I will look into the parent repo, and maybe there I will create a new issue and create PR there as well. Thanks for replying.
